modLoader="kotlinforforge"
loaderVersion="[5,)"

issueTrackerURL="https://github.com/SirEdvin/UnlimitedPeripheralWorks/issues"
logoFile="pack.png"

license="MIT"

[[mods]]
modId="peripheralworks"
version="${file.jarVersion}"
displayName="UnlimitedPeripheralWorks"
displayURL="https://docs.siredvin.site/UnlimitedPeripheralWorks/"

credits=""
authors="SirEdvin"
description='''
Peripheral mod, that provides a lot extra features, new peripherals and even some items
'''

[[dependencies.peripheralworks]]
modId="neoforge"
type="required"
versionRange="[${neoforgeVersion},21.2)"
ordering="NONE"
side="BOTH"

[[dependencies.peripheralworks]]
modId="minecraft"
type="required"
versionRange="[1.21.1,1.21.2)"
ordering="NONE"
side="BOTH"

[[dependencies.peripheralworks]]
modId="computercraft"
type="required"
versionRange="[${computercraftVersion},)"
ordering="NONE"
side="BOTH"

[[dependencies.peripheralworks]]
modId="peripheralium"
type="required"
versionRange="[${peripheraliumVersion},)"
ordering="NONE"
side="BOTH"

[[dependencies.peripheralworks]]
modId="broccolium"
type="required"
versionRange="[${broccoliumVersion},)"
ordering="NONE"
side="BOTH"

[[dependencies.peripheralworks]]
modId="tweakium"
type="required"
versionRange="[${tweakiumVersion},)"
ordering="NONE"
side="BOTH"
